export type PapereriaCategorySeed = {
  name: string;
  slug: string;
  imageUrl: string;
};

export type PapereriaProductSeed = {
  title: string;
  slug: string;
  categorySlug: string;
  description: string;
  imageUrls: string[];
  presentations: string[];
  colors: string[];
  price: number;
  weight: number;
  width: number;
  height: number;
  length: number;
};

const imageLibrary = {
  booksOpen:
    'https://images.pexels.com/photos/19561464/pexels-photo-19561464.jpeg?cs=srgb&dl=pexels-jessikaarraes-19561464.jpg&fm=jpg',
  booksShelf:
    'https://images.pexels.com/photos/9277357/pexels-photo-9277357.jpeg?cs=srgb&dl=pexels-dastan-9277357.jpg&fm=jpg',
  atlas:
    'https://images.pexels.com/photos/15835241/pexels-photo-15835241.jpeg?cs=srgb&dl=pexels-arturoaez225-15835241.jpg&fm=jpg',
  schoolKit:
    'https://images.pexels.com/photos/5445616/pexels-photo-5445616.jpeg?cs=srgb&dl=pexels-lulizler-5445616.jpg&fm=jpg',
  sharpener:
    'https://images.pexels.com/photos/33890774/pexels-photo-33890774.jpeg?cs=srgb&dl=pexels-christina99999-33890774.jpg&fm=jpg',
  notebookBlue:
    'https://images.pexels.com/photos/28503364/pexels-photo-28503364.jpeg?cs=srgb&dl=pexels-the-design-lady-746806315-28503364.jpg&fm=jpg',
  pencilsCup:
    'https://images.pexels.com/photos/28503353/pexels-photo-28503353.jpeg?cs=srgb&dl=pexels-the-design-lady-746806315-28503353.jpg&fm=jpg',
  pencilsCircle:
    'https://images.pexels.com/photos/23229781/pexels-photo-23229781.jpeg?cs=srgb&dl=pexels-agustina-sobnno-81431993-23229781.jpg&fm=jpg',
  classroom:
    'https://images.pexels.com/photos/8499575/pexels-photo-8499575.jpeg?cs=srgb&dl=pexels-rdne-8499575.jpg&fm=jpg',
  gummies:
    'https://images.pexels.com/photos/28114786/pexels-photo-28114786.jpeg?cs=srgb&dl=pexels-ana-vieira-1110685065-28114786.jpg&fm=jpg',
  lollipop:
    'https://images.pexels.com/photos/6037899/pexels-photo-6037899.jpeg?cs=srgb&dl=pexels-vikaemerson-6037899.jpg&fm=jpg',
  candyWindow:
    'https://images.pexels.com/photos/35045990/pexels-photo-35045990.jpeg?cs=srgb&dl=pexels-monurblc-35045990.jpg&fm=jpg',
  sweetShowcase:
    'https://images.pexels.com/photos/6161674/pexels-photo-6161674.jpeg?cs=srgb&dl=pexels-meruyert-gonullu-6161674.jpg&fm=jpg',
  confettiBalloons:
    'https://images.pexels.com/photos/796606/pexels-photo-796606.jpeg?cs=srgb&dl=pexels-nietjuhart-796606.jpg&fm=jpg',
  pinkBalloons:
    'https://images.pexels.com/photos/20362906/pexels-photo-20362906.jpeg?cs=srgb&dl=pexels-alexquezada-20362906.jpg&fm=jpg',
  pastelBalloons:
    'https://images.pexels.com/photos/3905853/pexels-photo-3905853.jpeg?cs=srgb&dl=pexels-polina-tankilevitch-3905853.jpg&fm=jpg',
  partyTraffic:
    'https://images.pexels.com/photos/32370581/pexels-photo-32370581.jpeg?cs=srgb&dl=pexels-jonathanborba-32370581.jpg&fm=jpg',
  pinkCandyBar:
    'https://images.pexels.com/photos/35224360/pexels-photo-35224360.jpeg?cs=srgb&dl=pexels-jonathanborba-35224360.jpg&fm=jpg',
} as const;

export const PAPERERIA_CATEGORIES: PapereriaCategorySeed[] = [
  {
    name: 'Libros',
    slug: 'libros',
    imageUrl: imageLibrary.booksOpen,
  },
  {
    name: 'Papeleria',
    slug: 'papeleria',
    imageUrl: imageLibrary.notebookBlue,
  },
  {
    name: 'Utiles escolares',
    slug: 'utiles-escolares',
    imageUrl: imageLibrary.schoolKit,
  },
  {
    name: 'Artistica',
    slug: 'artistica',
    imageUrl: imageLibrary.pencilsCircle,
  },
  {
    name: 'Golosinas',
    slug: 'golosinas',
    imageUrl: imageLibrary.candyWindow,
  },
  {
    name: 'Cotillon',
    slug: 'cotillon',
    imageUrl: imageLibrary.confettiBalloons,
  },
];

export const PAPERERIA_PRODUCTS: PapereriaProductSeed[] = [
  {
    title: 'Cuentos para Sonar',
    slug: 'cuentos-para-sonar',
    categorySlug: 'libros',
    description:
      'Libro infantil para regalar o sumar a la mesa principal de lectura, pensado como producto ancla para una papeleria con propuestas familiares.',
    imageUrls: [imageLibrary.booksOpen, imageLibrary.booksShelf],
    presentations: ['Tapa blanda', 'Tapa dura'],
    colors: ['Multicolor'],
    price: 15990,
    weight: 0.38,
    width: 16,
    height: 2,
    length: 24,
  },
  {
    title: 'Atlas Escolar Ilustrado',
    slug: 'atlas-escolar-ilustrado',
    categorySlug: 'libros',
    description:
      'Atlas de consulta para primaria y secundaria, ideal para vidriera escolar y compras de temporada.',
    imageUrls: [imageLibrary.atlas, imageLibrary.booksOpen],
    presentations: ['Edicion escolar', 'Edicion ampliada'],
    colors: ['Multicolor'],
    price: 21990,
    weight: 0.54,
    width: 22,
    height: 2.2,
    length: 29,
  },
  {
    title: 'Novela Juvenil Verano Rosa',
    slug: 'novela-juvenil-verano-rosa',
    categorySlug: 'libros',
    description:
      'Novela juvenil de mostrador para sumar impulso de compra junto a agendas, stickers y regalos pequenos.',
    imageUrls: [imageLibrary.booksShelf, imageLibrary.booksOpen],
    presentations: ['Tapa blanda', 'Edicion especial'],
    colors: ['Rosa pastel'],
    price: 18490,
    weight: 0.33,
    width: 15,
    height: 2,
    length: 23,
  },
  {
    title: 'Libro de Actividades Creativas',
    slug: 'libro-de-actividades-creativas',
    categorySlug: 'libros',
    description:
      'Libro con ejercicios, juegos y paginas para colorear, pensado para complementar utiles y artistica.',
    imageUrls: [imageLibrary.booksOpen, imageLibrary.classroom],
    presentations: ['A4', 'A5'],
    colors: ['Surtido'],
    price: 12990,
    weight: 0.29,
    width: 21,
    height: 1.4,
    length: 29,
  },
  {
    title: 'Cuaderno Rayado Pastel A4',
    slug: 'cuaderno-rayado-pastel-a4',
    categorySlug: 'papeleria',
    description:
      'Cuaderno rayado de tapa suave para uso diario, exhibicion de vuelta al cole y compras de oficina hogarena.',
    imageUrls: [imageLibrary.notebookBlue, imageLibrary.pencilsCup],
    presentations: ['A4', 'A5'],
    colors: ['Rosa', 'Celeste', 'Lila'],
    price: 6990,
    weight: 0.26,
    width: 21,
    height: 1.2,
    length: 29,
  },
  {
    title: 'Agenda Semanal Rosa Pastel',
    slug: 'agenda-semanal-rosa-pastel',
    categorySlug: 'papeleria',
    description:
      'Agenda de escritorio para organizar clases, trabajo y pendientes, con look suave para regaleria escolar.',
    imageUrls: [imageLibrary.notebookBlue, imageLibrary.booksOpen],
    presentations: ['Semanal', 'Diaria'],
    colors: ['Rosa pastel', 'Beige'],
    price: 11990,
    weight: 0.34,
    width: 17,
    height: 2,
    length: 24,
  },
  {
    title: 'Block de Notas Adhesivas Neon',
    slug: 'block-de-notas-adhesivas-neon',
    categorySlug: 'papeleria',
    description:
      'Pack de notas autoadhesivas para escritorio, escuela y estudio, con mucho color para zonas de caja y combo rapido.',
    imageUrls: [imageLibrary.schoolKit, imageLibrary.sharpener],
    presentations: ['Pack x3', 'Pack x6'],
    colors: ['Neon mix'],
    price: 3990,
    weight: 0.09,
    width: 8,
    height: 3,
    length: 8,
  },
  {
    title: 'Set de Lapiceras Gel Brillo',
    slug: 'set-de-lapiceras-gel-brillo',
    categorySlug: 'papeleria',
    description:
      'Lapiceras de trazo suave para tomar apuntes, journaling y regalos escolares de bajo ticket.',
    imageUrls: [imageLibrary.pencilsCup, imageLibrary.notebookBlue],
    presentations: ['Pack x6', 'Pack x12'],
    colors: ['Pastel mix', 'Metalizadas'],
    price: 8490,
    weight: 0.16,
    width: 12,
    height: 2,
    length: 18,
  },
  {
    title: 'Kit Vuelta al Cole x20',
    slug: 'kit-vuelta-al-cole-x20',
    categorySlug: 'utiles-escolares',
    description:
      'Combo surtido de utiles basicos para armar promociones fuertes de inicio de clases y regalos practicos.',
    imageUrls: [imageLibrary.schoolKit, imageLibrary.classroom],
    presentations: ['Kit basico', 'Kit completo'],
    colors: ['Surtido'],
    price: 24990,
    weight: 0.88,
    width: 28,
    height: 8,
    length: 34,
  },
  {
    title: 'Combo Mochila y Cartuchera',
    slug: 'combo-mochila-y-cartuchera',
    categorySlug: 'utiles-escolares',
    description:
      'Combo visual para destacar en home, pensado como producto de ticket medio para campana escolar.',
    imageUrls: [imageLibrary.pencilsCup, imageLibrary.classroom],
    presentations: ['Infantil', 'Junior'],
    colors: ['Rosa', 'Azul'],
    price: 42990,
    weight: 0.95,
    width: 32,
    height: 10,
    length: 42,
  },
  {
    title: 'Set de Lapices de Color x12',
    slug: 'set-de-lapices-de-color-x12',
    categorySlug: 'utiles-escolares',
    description:
      'Clasico de mostrador para complementar cuadernos, blocks y libros de actividades.',
    imageUrls: [imageLibrary.pencilsCircle, imageLibrary.pencilsCup],
    presentations: ['Pack x12', 'Pack x24'],
    colors: ['Clasico', 'Pastel'],
    price: 5890,
    weight: 0.14,
    width: 10,
    height: 2,
    length: 19,
  },
  {
    title: 'Regla Goma y Sacapuntas',
    slug: 'regla-goma-y-sacapuntas',
    categorySlug: 'utiles-escolares',
    description:
      'Pack economico para impulso de compra y armado de combos escolares a buen precio.',
    imageUrls: [imageLibrary.sharpener, imageLibrary.schoolKit],
    presentations: ['Pack x1', 'Pack x3'],
    colors: ['Rosa', 'Verde', 'Transparente'],
    price: 3490,
    weight: 0.08,
    width: 6,
    height: 3,
    length: 20,
  },
  {
    title: 'Marcadores Escolares x24',
    slug: 'marcadores-escolares-x24',
    categorySlug: 'artistica',
    description:
      'Set de marcadores de punta fina para dibujar, decorar y completar trabajos practicos.',
    imageUrls: [imageLibrary.pencilsCircle, imageLibrary.schoolKit],
    presentations: ['Pack x12', 'Pack x24'],
    colors: ['Surtido'],
    price: 10990,
    weight: 0.24,
    width: 15,
    height: 2.5,
    length: 22,
  },
  {
    title: 'Crayones Triangulares x12',
    slug: 'crayones-triangulares-x12',
    categorySlug: 'artistica',
    description:
      'Crayones pensados para nivel inicial, faciles de exhibir y perfectos para combos de actividades.',
    imageUrls: [imageLibrary.pencilsCircle, imageLibrary.classroom],
    presentations: ['Pack x12', 'Pack x24'],
    colors: ['Clasico', 'Pastel'],
    price: 6490,
    weight: 0.18,
    width: 13,
    height: 2,
    length: 18,
  },
  {
    title: 'Set de Temperas Pastel',
    slug: 'set-de-temperas-pastel',
    categorySlug: 'artistica',
    description:
      'Tempera escolar para tareas de artistica y manualidades, con una paleta amable para la identidad del theme.',
    imageUrls: [imageLibrary.schoolKit, imageLibrary.pencilsCup],
    presentations: ['Pack x6', 'Pack x12'],
    colors: ['Pastel mix'],
    price: 7990,
    weight: 0.31,
    width: 14,
    height: 4,
    length: 18,
  },
  {
    title: 'Block de Dibujo A4',
    slug: 'block-de-dibujo-a4',
    categorySlug: 'artistica',
    description:
      'Block para lapiz, marcador y collage, ideal para exhibicion cruzada con lapices y crayones.',
    imageUrls: [imageLibrary.notebookBlue, imageLibrary.schoolKit],
    presentations: ['A4', 'A3'],
    colors: ['Blanco'],
    price: 7290,
    weight: 0.22,
    width: 21,
    height: 1.2,
    length: 29,
  },
  {
    title: 'Gomitas Frutales Surtidas',
    slug: 'gomitas-frutales-surtidas',
    categorySlug: 'golosinas',
    description:
      'Gomitas suaves para caja y mostrador, con imagen colorida para mockups y promos por impulso.',
    imageUrls: [imageLibrary.gummies, imageLibrary.candyWindow],
    presentations: ['Bolsa x100g', 'Bolsa x250g'],
    colors: ['Surtido'],
    price: 2990,
    weight: 0.12,
    width: 11,
    height: 4,
    length: 18,
  },
  {
    title: 'Paleta Arcoiris Gigante',
    slug: 'paleta-arcoiris-gigante',
    categorySlug: 'golosinas',
    description:
      'Paleta de alto impacto visual para sumar color a la categoria y a las mesas de cumpleaños.',
    imageUrls: [imageLibrary.lollipop, imageLibrary.gummies],
    presentations: ['Unidad', 'Pack x6'],
    colors: ['Arcoiris'],
    price: 2490,
    weight: 0.07,
    width: 5,
    height: 1.5,
    length: 18,
  },
  {
    title: 'Mix de Caramelos Masticables',
    slug: 'mix-de-caramelos-masticables',
    categorySlug: 'golosinas',
    description:
      'Mix dulce para frascos, zonas de espera y promociones de bajo ticket en caja.',
    imageUrls: [imageLibrary.candyWindow, imageLibrary.sweetShowcase],
    presentations: ['Bolsa x200g', 'Frasco x400g'],
    colors: ['Surtido'],
    price: 4590,
    weight: 0.23,
    width: 12,
    height: 6,
    length: 20,
  },
  {
    title: 'Dulces de Mostrador Premium',
    slug: 'dulces-de-mostrador-premium',
    categorySlug: 'golosinas',
    description:
      'Surtido premium para una zona dulce mas vistosa, pensado como referencia para pasteleria y candy bar.',
    imageUrls: [imageLibrary.sweetShowcase, imageLibrary.candyWindow],
    presentations: ['Caja chica', 'Caja mediana'],
    colors: ['Surtido'],
    price: 8990,
    weight: 0.42,
    width: 18,
    height: 6,
    length: 22,
  },
  {
    title: 'Globos Perlados Pack x10',
    slug: 'globos-perlados-pack-x10',
    categorySlug: 'cotillon',
    description:
      'Pack de globos de acabado perlado para vidriera de fiestas, mesas dulces y ambientaciones rapidas.',
    imageUrls: [imageLibrary.pinkBalloons, imageLibrary.pastelBalloons],
    presentations: ['Pack x10', 'Pack x30'],
    colors: ['Rosa', 'Dorado', 'Pastel mix'],
    price: 5990,
    weight: 0.11,
    width: 12,
    height: 3,
    length: 18,
  },
  {
    title: 'Guirnalda Feliz Cumple',
    slug: 'guirnalda-feliz-cumple',
    categorySlug: 'cotillon',
    description:
      'Guirnalda decorativa para fechas especiales, facil de sumar a combos de salon o casa.',
    imageUrls: [imageLibrary.confettiBalloons, imageLibrary.partyTraffic],
    presentations: ['Clasica', 'Metalizada'],
    colors: ['Rosa', 'Multicolor'],
    price: 5290,
    weight: 0.09,
    width: 17,
    height: 2,
    length: 20,
  },
  {
    title: 'Kit Deco Mesa Dulce',
    slug: 'kit-deco-mesa-dulce',
    categorySlug: 'cotillon',
    description:
      'Kit para ambientar candy bar y mesa central, ideal para mostrar el costado mas festivo de la tienda.',
    imageUrls: [imageLibrary.pinkCandyBar, imageLibrary.pinkBalloons],
    presentations: ['Kit chico', 'Kit completo'],
    colors: ['Rosa pastel', 'Dorado'],
    price: 17990,
    weight: 0.46,
    width: 24,
    height: 8,
    length: 30,
  },
  {
    title: 'Combo Fiesta Infantil Vial',
    slug: 'combo-fiesta-infantil-vial',
    categorySlug: 'cotillon',
    description:
      'Combo tematico con visual muy potente para cumpleaños infantiles y vidriera de eventos.',
    imageUrls: [imageLibrary.partyTraffic, imageLibrary.confettiBalloons],
    presentations: ['Pack x8', 'Pack x16'],
    colors: ['Multicolor'],
    price: 23990,
    weight: 0.68,
    width: 28,
    height: 10,
    length: 34,
  },
  {
    title: 'Libro para Colorear Animales',
    slug: 'libro-para-colorear-animales',
    categorySlug: 'libros',
    description:
      'Titulo de rotacion rapida para infancia, pensado para venderse junto a crayones, lapices y sets escolares.',
    imageUrls: [imageLibrary.booksOpen, imageLibrary.classroom],
    presentations: ['A4', 'A5'],
    colors: ['Surtido'],
    price: 9990,
    weight: 0.26,
    width: 21,
    height: 1.2,
    length: 29,
  },
  {
    title: 'Enciclopedia Escolar Visual',
    slug: 'enciclopedia-escolar-visual',
    categorySlug: 'libros',
    description:
      'Referencia visual para mesas de estudio y utiles, ideal para un boceto de libreria con foco escolar.',
    imageUrls: [imageLibrary.atlas, imageLibrary.booksShelf],
    presentations: ['Tapa dura', 'Tapa blanda'],
    colors: ['Multicolor'],
    price: 25990,
    weight: 0.62,
    width: 22,
    height: 2.6,
    length: 29,
  },
  {
    title: 'Coleccion Primeras Lecturas',
    slug: 'coleccion-primeras-lecturas',
    categorySlug: 'libros',
    description:
      'Pack literario para infancia temprana, muy util como combo regalo dentro de la tienda.',
    imageUrls: [imageLibrary.booksShelf, imageLibrary.booksOpen],
    presentations: ['Pack x3', 'Pack x5'],
    colors: ['Surtido'],
    price: 28990,
    weight: 0.58,
    width: 17,
    height: 4,
    length: 24,
  },
  {
    title: 'Diccionario Escolar Compacto',
    slug: 'diccionario-escolar-compacto',
    categorySlug: 'libros',
    description:
      'Producto funcional para temporada escolar, pensado para compras utilitarias y combos de estudio.',
    imageUrls: [imageLibrary.atlas, imageLibrary.booksOpen],
    presentations: ['Compacto', 'Ampliado'],
    colors: ['Azul', 'Rojo'],
    price: 14990,
    weight: 0.41,
    width: 14,
    height: 3,
    length: 21,
  },
  {
    title: 'Novela Clasica de Bolsillo',
    slug: 'novela-clasica-de-bolsillo',
    categorySlug: 'libros',
    description:
      'Edicion economica para sumar lectura general al surtido de una papelera de barrio.',
    imageUrls: [imageLibrary.booksOpen, imageLibrary.booksShelf],
    presentations: ['Bolsillo', 'Edicion especial'],
    colors: ['Arena', 'Rosa'],
    price: 11990,
    weight: 0.22,
    width: 12,
    height: 2,
    length: 19,
  },
  {
    title: 'Planner Mensual con Stickers',
    slug: 'planner-mensual-con-stickers',
    categorySlug: 'papeleria',
    description:
      'Planner con look amable para estudio, oficina y regalo, ideal para destacar en home y redes.',
    imageUrls: [imageLibrary.notebookBlue, imageLibrary.booksOpen],
    presentations: ['Mensual', 'Anual'],
    colors: ['Rosa pastel', 'Lila', 'Celeste'],
    price: 13990,
    weight: 0.36,
    width: 18,
    height: 2.2,
    length: 25,
  },
  {
    title: 'Carpeta Oficio con Elastico',
    slug: 'carpeta-oficio-con-elastico',
    categorySlug: 'papeleria',
    description:
      'Carpeta para hojas y trabajos practicos, pensada para compras escolares y de home office.',
    imageUrls: [imageLibrary.notebookBlue, imageLibrary.schoolKit],
    presentations: ['Oficio', 'A4'],
    colors: ['Rosa', 'Negro', 'Celeste'],
    price: 5490,
    weight: 0.2,
    width: 24,
    height: 1.5,
    length: 34,
  },
  {
    title: 'Resaltadores Pastel x6',
    slug: 'resaltadores-pastel-x6',
    categorySlug: 'papeleria',
    description:
      'Set de resaltadores para apuntes y journaling, con buena salida visual y ticket accesible.',
    imageUrls: [imageLibrary.pencilsCup, imageLibrary.schoolKit],
    presentations: ['Pack x6', 'Pack x12'],
    colors: ['Pastel mix'],
    price: 7990,
    weight: 0.13,
    width: 9,
    height: 2,
    length: 16,
  },
  {
    title: 'Set de Etiquetas Adhesivas',
    slug: 'set-de-etiquetas-adhesivas',
    categorySlug: 'papeleria',
    description:
      'Accesorio practico para cuadernos, carpetas y organizacion general, ideal para zona de caja.',
    imageUrls: [imageLibrary.schoolKit, imageLibrary.notebookBlue],
    presentations: ['Pack x24', 'Pack x48'],
    colors: ['Blanco', 'Pastel'],
    price: 2990,
    weight: 0.05,
    width: 8,
    height: 1,
    length: 13,
  },
  {
    title: 'Cuaderno Universitario x84 Hojas',
    slug: 'cuaderno-universitario-x84-hojas',
    categorySlug: 'papeleria',
    description:
      'Clasico de cursada y oficina para completar el surtido base de la papelera.',
    imageUrls: [imageLibrary.notebookBlue, imageLibrary.pencilsCup],
    presentations: ['Rayado', 'Cuadriculado'],
    colors: ['Azul', 'Rosa', 'Verde'],
    price: 8790,
    weight: 0.31,
    width: 21,
    height: 1.5,
    length: 27,
  },
  {
    title: 'Cartuchera Simple Escolar',
    slug: 'cartuchera-simple-escolar',
    categorySlug: 'utiles-escolares',
    description:
      'Complemento natural para kits escolares, visible y facil de vender en varias edades.',
    imageUrls: [imageLibrary.pencilsCup, imageLibrary.classroom],
    presentations: ['Simple', 'Doble cierre'],
    colors: ['Rosa', 'Azul', 'Negro'],
    price: 6990,
    weight: 0.17,
    width: 10,
    height: 4,
    length: 22,
  },
  {
    title: 'Tijera Escolar Punta Redonda',
    slug: 'tijera-escolar-punta-redonda',
    categorySlug: 'utiles-escolares',
    description:
      'Basico escolar para combos de inicio de clases y reposiciones rapidas.',
    imageUrls: [imageLibrary.schoolKit, imageLibrary.sharpener],
    presentations: ['Unidad', 'Pack x3'],
    colors: ['Verde', 'Rosa', 'Azul'],
    price: 3290,
    weight: 0.08,
    width: 7,
    height: 1.5,
    length: 15,
  },
  {
    title: 'Plasticola Escolar 250g',
    slug: 'plasticola-escolar-250g',
    categorySlug: 'utiles-escolares',
    description:
      'Producto recurrente para primaria y manualidades, bueno para bocetar compra por volumen.',
    imageUrls: [imageLibrary.schoolKit, imageLibrary.classroom],
    presentations: ['250g', '500g'],
    colors: ['Blanco'],
    price: 2790,
    weight: 0.27,
    width: 6,
    height: 16,
    length: 6,
  },
  {
    title: 'Compas Escolar Metalico',
    slug: 'compas-escolar-metalico',
    categorySlug: 'utiles-escolares',
    description:
      'Util de geometria para secundaria, ideal para ampliar el mix de utiles duros.',
    imageUrls: [imageLibrary.schoolKit, imageLibrary.sharpener],
    presentations: ['Unidad', 'Set geometria'],
    colors: ['Metal', 'Negro'],
    price: 4990,
    weight: 0.09,
    width: 5,
    height: 2,
    length: 17,
  },
  {
    title: 'Set Geometria Transparente',
    slug: 'set-geometria-transparente',
    categorySlug: 'utiles-escolares',
    description:
      'Regla, escuadra y transportador para listas escolares y compra de reposicion.',
    imageUrls: [imageLibrary.schoolKit, imageLibrary.sharpener],
    presentations: ['Pack x3', 'Pack x4'],
    colors: ['Transparente', 'Pastel'],
    price: 4590,
    weight: 0.12,
    width: 12,
    height: 1.5,
    length: 22,
  },
  {
    title: 'Acuarelas Escolares x12',
    slug: 'acuarelas-escolares-x12',
    categorySlug: 'artistica',
    description:
      'Set colorido para primaria y talleres, con buena lectura visual para catalogo de muestra.',
    imageUrls: [imageLibrary.pencilsCircle, imageLibrary.schoolKit],
    presentations: ['Pack x12', 'Pack x24'],
    colors: ['Surtido'],
    price: 8990,
    weight: 0.19,
    width: 15,
    height: 2,
    length: 21,
  },
  {
    title: 'Pinceles Escolares x5',
    slug: 'pinceles-escolares-x5',
    categorySlug: 'artistica',
    description:
      'Complemento ideal para temperas y acuarelas, pensado para armar combos artistica.',
    imageUrls: [imageLibrary.pencilsCup, imageLibrary.schoolKit],
    presentations: ['Pack x5', 'Pack x10'],
    colors: ['Madera', 'Pastel'],
    price: 4690,
    weight: 0.07,
    width: 4,
    height: 2,
    length: 20,
  },
  {
    title: 'Masa para Modelar x6',
    slug: 'masa-para-modelar-x6',
    categorySlug: 'artistica',
    description:
      'Producto de alta rotacion en infancia y jardin, con valor para temporadas escolares.',
    imageUrls: [imageLibrary.classroom, imageLibrary.pencilsCircle],
    presentations: ['Pack x6', 'Pack x12'],
    colors: ['Surtido'],
    price: 5590,
    weight: 0.24,
    width: 12,
    height: 3,
    length: 18,
  },
  {
    title: 'Fibrones Lavables x10',
    slug: 'fibrones-lavables-x10',
    categorySlug: 'artistica',
    description:
      'Set para manualidades y carteleria escolar, pensado para boceto con mucho color.',
    imageUrls: [imageLibrary.pencilsCircle, imageLibrary.classroom],
    presentations: ['Pack x10', 'Pack x20'],
    colors: ['Clasico', 'Neon'],
    price: 9490,
    weight: 0.21,
    width: 14,
    height: 2.5,
    length: 19,
  },
  {
    title: 'Cartulina Color Pack x10',
    slug: 'cartulina-color-pack-x10',
    categorySlug: 'artistica',
    description:
      'Pack para collage, laminas y trabajos manuales, muy util para un surtido escolar completo.',
    imageUrls: [imageLibrary.schoolKit, imageLibrary.notebookBlue],
    presentations: ['Pack x10', 'Pack x20'],
    colors: ['Surtido', 'Pastel'],
    price: 3890,
    weight: 0.16,
    width: 24,
    height: 1,
    length: 34,
  },
  {
    title: 'Chupetines Surtidos x24',
    slug: 'chupetines-surtidos-x24',
    categorySlug: 'golosinas',
    description:
      'Pack para mostrador y candy bar, pensado como producto impulsivo y decorativo.',
    imageUrls: [imageLibrary.lollipop, imageLibrary.candyWindow],
    presentations: ['Pack x24', 'Pack x48'],
    colors: ['Surtido'],
    price: 5290,
    weight: 0.31,
    width: 14,
    height: 5,
    length: 20,
  },
  {
    title: 'Caramelos Rellenos Frutales',
    slug: 'caramelos-rellenos-frutales',
    categorySlug: 'golosinas',
    description:
      'Opcion economica para caja y frasco, con gran valor de surtido para el mockup.',
    imageUrls: [imageLibrary.candyWindow, imageLibrary.gummies],
    presentations: ['Bolsa x150g', 'Bolsa x300g'],
    colors: ['Surtido'],
    price: 3190,
    weight: 0.18,
    width: 11,
    height: 4,
    length: 17,
  },
  {
    title: 'Pastillas Mentoladas',
    slug: 'pastillas-mentoladas',
    categorySlug: 'golosinas',
    description:
      'Producto chico y de alta rotacion para sumar variedad al sector de golosinas.',
    imageUrls: [imageLibrary.candyWindow, imageLibrary.sweetShowcase],
    presentations: ['Lata', 'Pack x6'],
    colors: ['Verde', 'Azul'],
    price: 2190,
    weight: 0.05,
    width: 5,
    height: 1.8,
    length: 7,
  },
  {
    title: 'Chocolate en Barra Mini',
    slug: 'chocolate-en-barra-mini',
    categorySlug: 'golosinas',
    description:
      'Mini chocolate para caja y combos de regalo, util para mostrar surtido dulce diverso.',
    imageUrls: [imageLibrary.sweetShowcase, imageLibrary.candyWindow],
    presentations: ['Unidad', 'Pack x12'],
    colors: ['Leche', 'Blanco'],
    price: 1890,
    weight: 0.04,
    width: 4,
    height: 1,
    length: 10,
  },
  {
    title: 'Mix Candy Bar Premium',
    slug: 'mix-candy-bar-premium',
    categorySlug: 'golosinas',
    description:
      'Seleccion para eventos, regalos y sector fiesta, muy util para cruces con cotillon.',
    imageUrls: [imageLibrary.pinkCandyBar, imageLibrary.sweetShowcase],
    presentations: ['Caja chica', 'Caja grande'],
    colors: ['Pastel', 'Surtido'],
    price: 13990,
    weight: 0.55,
    width: 20,
    height: 7,
    length: 24,
  },
  {
    title: 'Servilletas Tematicas x20',
    slug: 'servilletas-tematicas-x20',
    categorySlug: 'cotillon',
    description:
      'Accesorio infaltable para fiestas y candy bar, perfecto para completar el sector cotillon.',
    imageUrls: [imageLibrary.partyTraffic, imageLibrary.pinkCandyBar],
    presentations: ['Pack x20', 'Pack x40'],
    colors: ['Rosa', 'Multicolor'],
    price: 3490,
    weight: 0.09,
    width: 16,
    height: 2,
    length: 16,
  },
  {
    title: 'Vasos de Papel Fiesta x10',
    slug: 'vasos-de-papel-fiesta-x10',
    categorySlug: 'cotillon',
    description:
      'Complemento para mesa dulce y cumpleanos, pensado para combos listos para evento.',
    imageUrls: [imageLibrary.pinkCandyBar, imageLibrary.confettiBalloons],
    presentations: ['Pack x10', 'Pack x20'],
    colors: ['Rosa pastel', 'Dorado'],
    price: 3990,
    weight: 0.1,
    width: 8,
    height: 9,
    length: 8,
  },
  {
    title: 'Bengalas Frias Pack x4',
    slug: 'bengalas-frias-pack-x4',
    categorySlug: 'cotillon',
    description:
      'Producto visual para celebraciones y ambientacion de tortas, util para eventos.',
    imageUrls: [imageLibrary.confettiBalloons, imageLibrary.pastelBalloons],
    presentations: ['Pack x4', 'Pack x8'],
    colors: ['Plateado', 'Dorado'],
    price: 6990,
    weight: 0.08,
    width: 3,
    height: 1.5,
    length: 18,
  },
  {
    title: 'Cortina Metalizada Fondo',
    slug: 'cortina-metalizada-fondo',
    categorySlug: 'cotillon',
    description:
      'Fondo rapido para fotos y decoracion de fiestas, muy util para mockups de temporada.',
    imageUrls: [imageLibrary.pinkBalloons, imageLibrary.confettiBalloons],
    presentations: ['Unidad', 'Pack x2'],
    colors: ['Rosa', 'Plateado', 'Dorado'],
    price: 7490,
    weight: 0.16,
    width: 30,
    height: 3,
    length: 35,
  },
  {
    title: 'Topper de Torta Feliz Cumple',
    slug: 'topper-de-torta-feliz-cumple',
    categorySlug: 'cotillon',
    description:
      'Detalle de decoracion para fiestas, bueno para complementar candy bar y vajilla.',
    imageUrls: [imageLibrary.pinkCandyBar, imageLibrary.partyTraffic],
    presentations: ['Unidad', 'Pack x3'],
    colors: ['Dorado', 'Rosa'],
    price: 2890,
    weight: 0.04,
    width: 12,
    height: 1,
    length: 18,
  },
];
