export const PRODUCT_INVENTORY_POLICIES = ['UNCLASSIFIED', 'RESTOCK', 'NO_RESTOCK', 'UNTRACKED'] as const;
export type ProductInventoryPolicy = (typeof PRODUCT_INVENTORY_POLICIES)[number];

export const INVENTORY_MOVEMENT_TYPES = [
  'OPENING_BALANCE', 'INITIAL_LOAD', 'MANUAL_ADJUSTMENT', 'RESERVATION', 'RESERVATION_RELEASE',
  'SALE', 'CANCELLATION_RESTOCK', 'RETURN_RESTOCK', 'EXCHANGE_OUT', 'ORDER_EDIT',
  'TRIAL_RESERVATION', 'TRIAL_RELEASE', 'TRIAL_SALE', 'SYSTEM_CORRECTION',
] as const;
export type InventoryMovementType = (typeof INVENTORY_MOVEMENT_TYPES)[number];
