ALTER TABLE "Payment"
ADD COLUMN "method" TEXT,
ADD COLUMN "reference" TEXT,
ADD COLUMN "proofUrl" TEXT,
ADD COLUMN "proofFilename" TEXT,
ADD COLUMN "notes" TEXT,
ADD COLUMN "metadata" JSONB,
ADD COLUMN "reviewedAt" TIMESTAMP(3),
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
